services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "80:80"
      - "9101:9100"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - skylogs:/var/log/nginx
      - skywww:/var/www
    restart: always
    networks:
      - skynet
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
        ALPINE_VERSION: ${ALPINE_VERSION}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - skydb:/var/lib/mysql
    restart: always
    networks:
      - skynet
  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - skywww:/var/www
    restart: always
    networks:
      - skynet
  # grafana:
  #   image: grafana/grafana-oss:8.5.22
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   restart: always
  #   networks:
  #     - skynet
  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./requirements/prometheus/conf/:/etc/prometheus
    restart: always
    depends_on:
      - nginx
    networks:
      - skynet
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
  # nginx-exporter:
  #   image: nginx/nginx-prometheus-exporter
  #   environment:
  #       - SCRAPE_URI=http://localhost/metrics
  #       - TELEMETRY_PATH=/metrics
  #       - NGINX_RETRIES=10
  #   ports:
  #     - "9113:9113"
  #   container_name: nginx-exporter
  #   depends_on:
  #     - nginx
  #   networks:
  #     - skynet
networks:
  skynet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
volumes:
  skylogs:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '$HOME/Inception/project/data/logs'
  skydb:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '$HOME/Inception/project/data/database'
  skywww:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '$HOME/Inception/project/data/www'
  grafana-data:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '$HOME/Inception/project/data/grafana_data'
  prometheus-data:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '$HOME/Inception/project/data/prometheus_data'
