services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - skywww:/usr/share/nginx/www
    restart: always
    networks:
      skynet:
        ipv4_address: 192.168.92.21
  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
        ALPINE_VERSION: ${ALPINE_VERSION}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - skydb:/var/lib/mysql
    restart: always
    networks:
      skynet:
        ipv4_address: 192.168.92.22
networks:
  skynet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"
volumes:
  skydb:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/anton/Inception/project/data/database'
  skywww:
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/anton/Inception/project/data/www'
